name: A job to Mute Alerts
run-name: "Mute Alerts for Splunk"

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Start time of mute_alert"
        required: true
        type: string
      end:
        description: "End time of mute_alert"
        required: true
        type: string
      dc:
        description: "Name of DC"
        required: true
        type: string

permissions:
  actions: read
  checks: read

env:
  SIGNALFX_API_URL: "https://rakesh-opendnsbu-sse.signalfx.com/v2"

jobs:
  Mute_Alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: GitHub Context Debug
        run: |
          echo $JSON | jq
        env:
          JSON: ${{ toJSON(github) }}

      - name: Run Mute Alerts Script
        shell: bash
       # working-directory: ./cloud/Mute_Alerts
        run: |
          # make run-script start=${{ github.event.inputs.start }} end=${{ github.event.inputs.end }} dc=${{ github.event.inputs.dc }}
          echo Hello, world!
          echo "start_Time=${{ github.event.inputs.start }}"
        env:
          SFX_AUTH_TOKEN: ${{ secrets.SFX_AUTH_TOKEN }}
