name:  Approve AMI for Prod"

on:
  workflow_dispatch:
    inputs:
      type:
        description: "Node type"
        required: true
        type: choice
        default: proxy
        options:
          - proxy
          - nidz
          - prom
          - enclave
      version:
        description: "Version"
        required: true
        type: string

permissions:
   contents: read

# jobs:
#   bless:
#     uses: ./.github/workflows/ami_approve_workflow_call.yml
#     with:
#       type: ${{ github.event.inputs.type }}
#       version: ${{ github.event.inputs.version }}
#       target: prod
#     secrets:
#       alerts_webhook_url: ${{ secrets.BAP_ALERTS_WEBHOOK_URL }}
