name: Mute Alerts for Splunk

on:
  workflow_call:
    inputs:
      start:
        description: "Start time of mute_alert"
        required: true
        type: string
      end:
        description: "End time of mute_alert"
        required: true
        type: string
      dc:
        description: "Name of DC"
        required: true
        type: string

env:
  SIGNALFX_API_URL: "https://rakesh-opendnsbu-sse.signalfx.com/v2"

jobs:
  mute_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: rakesh2525/Practice
          ref: main

      # - name: GitHub Context Debug
      #   run: echo "${{ toJSON(github) }}" | jq

      - name: Run Mute Alerts Script
        shell: bash
        working-directory: ./devop/
        run: |
          chmod +x hi.sh
          ./hi.sh
          echo "start_Time=${{ inputs.start }}"
        # env:
        #   SFX_AUTH_TOKEN: ${{ secrets.SFX_AUTH_TOKEN }}
