name: CI
on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch:
     inputs:
       start:
         description: "start_time"
         required: true
       end:
         description: "end_time"
         required: true

jobs:
 
  build:
    runs-on: ubuntu-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run:  |
           aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws_secret_access_key = ${{ secrets.AWS_SECRET_KEY_ID }}
           region = "us-east-1"
           export password=$(aws --region us-east-1 secretsmanager get-secret-value --query secretstring --secret-id --output text cicd/splunk_password)
           echo Hello, world!
           env

     
