name: CI
on:
  workflow_dispatch:
     inputs:
       start:
         description: "start_time"
         required: true
       end:
         description: "end_time"
         required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_KEY_ID }}
          export REGION="us-east-1"
          export PASSWORD=$(aws --region $REGION secretsmanager get-secret-value --query secretstring --secret-id cicd/splunk_password --output text)
          echo Hello, world!
          echo "start_time: $start"
          
